replicaCount: 1

image:
  repository: mallireddy1998/product-service:6
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 4882

resources: 
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 1000m
    memory: 1024Mi
