apiVersion: v1
kind: Service
metadata:
  name: cart-service
  labels:
    app: cartservice
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: app-port
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
     app: cartservice