replicaCount: 1

image:
  repository: mallireddy1998/product-service:"5"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 4882


resources: 
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi