apiVersion: v1
kind: Service
metadata:
  name: demoservice
  labels:
    app: demoservice
spec:
  ports:
    - port: 80
      targetPort: 1186
      protocol: TCP
  selector:
    app: demoservice
  type: NodePort