apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: orderservice
spec:
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
        - name: orderservice
          image: {{ .Values.image }}
          livenessProbe:
            httpGet:
              port: {{ .Values.service.port }}
              path: /actuator/health/liveness
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              port: {{ .Values.service.port }}
              path: /actuator/health/readiness
            initialDelaySeconds: 60
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.port }}