apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: productservice
spec:
  selector:
    matchLabels:
      app: productservice
  template:
    metadata:
      labels:
        app: productservice
    spec:
      containers:
        - name: productservice
          image: {{ .Values.image.repository }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            httpGet:
              port: {{ .Values.service.port }}
              path: /actuator/health/liveness
            initialDelaySeconds: 300
            periodSeconds: 20
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              port: {{ .Values.service.port }}
              path: /actuator/health/readiness
            initialDelaySeconds: 300
            periodSeconds: 20
            timeoutSeconds: 10
          #resources:
           # {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.port }}