replicaCount: 1

image:
  repository: mallireddy1998/order-service:"4"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 1645


resources: 
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi